/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Home_gallery = {
  _id: string;
  _type: 'home_gallery';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  images?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    _key: string;
  }>;
};

export type Home_events = {
  _id: string;
  _type: 'home_events';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  short_description?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
};

export type Home_team_member = {
  _id: string;
  _type: 'home_team_member';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  short_description?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  membersList?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'team_members';
  }>;
};

export type Home_partners = {
  _id: string;
  _type: 'home_partners';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
};

export type Home_testimonial = {
  _id: string;
  _type: 'home_testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  select_testimonials?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'testimonials_list';
  }>;
};

export type Testimonials_list = {
  _id: string;
  _type: 'testimonials_list';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user_name?: string;
  content?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  role?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'team_member_roles';
  };
};

export type Home_stats = {
  _id: string;
  _type: 'home_stats';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  select_stats?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'organizationStats';
  }>;
};

export type Featured_projects = {
  _id: string;
  _type: 'featured_projects';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  content?: Array<{
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    _key: string;
  }>;
};

export type Homepage_anepal = {
  _id: string;
  _type: 'homepage_anepal';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
  };
  membersDetails?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
    membersList?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'team_members';
    }>;
  };
};

export type Org_helps_in_fields = {
  _id: string;
  _type: 'org_helps_in_fields';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  content?: Array<{
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    _key: string;
  }>;
};

export type EventsPage = {
  _id: string;
  _type: 'eventsPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
};

export type StoriesPageContent = {
  _id: string;
  _type: 'storiesPageContent';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
  };
};

export type StoriesList = {
  _id: string;
  _type: 'storiesList';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  content?: {
    content_en?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'normal' | 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
          listItem?: 'bullet' | 'number' | 'checkmarks';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
          _key: string;
        }
    >;
    content_es?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'normal' | 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
          listItem?: 'bullet' | 'number' | 'checkmarks';
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
          _key: string;
        }
    >;
  };
};

export type OrganizationStats = {
  _id: string;
  _type: 'organizationStats';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  value?: string;
};

export type PartnersList = {
  _id: string;
  _type: 'partnersList';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  partnersName?: string;
  partnersLogo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type DonorsList = {
  _id: string;
  _type: 'donorsList';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  donorsName?: string;
};

export type DonorsAndPartnersPage = {
  _id: string;
  _type: 'donorsAndPartnersPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
  };
  whoHelpUsSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
    partnersName?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'partnersList';
    }>;
    donorsNames?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'donorsList';
    }>;
  };
  statisticsSection?: {
    statsTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    statsSubtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    statsDescription?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
    statistics?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'organizationStats';
    }>;
  };
  thankYouSection?: {
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
  };
};

export type Team_members_page = {
  _id: string;
  _type: 'team_members_page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
  };
  membersDetails?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
    membersList?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'team_members';
    }>;
  };
};

export type Team_members = {
  _id: string;
  _type: 'team_members';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  name?: string;
  short_intro?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  role?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'team_member_roles';
  };
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
  };
};

export type Team_member_roles = {
  _id: string;
  _type: 'team_member_roles';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type Aboutus = {
  _id: string;
  _type: 'aboutus';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
  };
  firstcontent?: {
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
  };
  secondcontent?: {
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    description?: Array<
      {
        _key: string;
      } & InternationalizedArrayTextValue
    >;
  };
  statisticsSection?: {
    statsTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    statsSubtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    statistics?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'organizationStats';
    }>;
  };
  teamsSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    teamMembers?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'team_members';
    }>;
  };
  partnersSection?: {
    title?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    highlightTitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    subtitle?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    partner?: Array<{
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: 'partnersList';
    }>;
  };
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet' | 'number' | 'checkmarks';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type Events = {
  _id: string;
  _type: 'events';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  slug?: Slug;
  featured?: boolean;
  short_description?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  organizer_info?: {
    phone?: number;
    email?: string;
  };
  venue?: {
    location?: string;
  };
  event_time?: {
    start?: string;
    end?: string;
  };
  body?: {
    body_en?: BlockContent;
    body_es?: BlockContent;
  };
};

export type WhatMakesUsUnique = {
  _id: string;
  _type: 'what-makes-us-unique';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type AboutAnepal = {
  _id: string;
  _type: 'about-anepal';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  subtitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayTextValue
  >;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type HomeContent = {
  _id: string;
  _type: 'home-content';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  Identifier?: string;
  name?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  order?: number;
  link?: string;
  subLinks?: Array<{
    Identifier?: string;
    name?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    link?: string;
    _key: string;
  }>;
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  contact?: {
    address?: string;
    phone?: string;
    email?: string;
  };
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    youtube?: string;
  };
};

export type Header = {
  _id: string;
  _type: 'header';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  link?: string;
  subLinks?: Array<{
    Identifier?: string;
    name?: Array<
      {
        _key: string;
      } & InternationalizedArrayStringValue
    >;
    link?: string;
    _key: string;
  }>;
};

export type HomeBanner = {
  _id: string;
  _type: 'home-banner';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  highlightTitle?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  description?: Array<
    {
      _key: string;
    } & InternationalizedArrayStringValue
  >;
  link?: string;
};

export type InternationalizedArrayTextValue = {
  _type: 'internationalizedArrayTextValue';
  value?: string;
};

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue';
  value?: string;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Home_gallery
  | Home_events
  | Home_team_member
  | Home_partners
  | Home_testimonial
  | Testimonials_list
  | Home_stats
  | Featured_projects
  | Homepage_anepal
  | Org_helps_in_fields
  | EventsPage
  | StoriesPageContent
  | StoriesList
  | OrganizationStats
  | PartnersList
  | DonorsList
  | DonorsAndPartnersPage
  | Team_members_page
  | Team_members
  | Team_member_roles
  | Aboutus
  | BlockContent
  | Events
  | WhatMakesUsUnique
  | AboutAnepal
  | HomeContent
  | Settings
  | Header
  | HomeBanner
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayText
  | InternationalizedArrayString
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
