import { baseUrl } from '@/constants';
import { getServerSideSitemapIndex } from 'next-sitemap';

export async function GET() {
  // List all your sitemaps here
  const sitemaps = [
    // Static pages sitemap (generated by next-sitemap)
    `${baseUrl}/sitemap-0.xml`,
    // Dynamic pages sitemap (generated by your server route)
    `${baseUrl}/server-sitemap.xml`
  ];

  return getServerSideSitemapIndex(sitemaps);
}
